### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by abhirajgupta** [ikkiChung/MyRealTimeImageProcessing#1]
dude , it is installing on the device , it says 
2014-06-14 18:05:44 - ddms] null
java.lang.NullPointerException
    at com.android.ide.eclipse.adt.internal.launch.DeviceChooserDialog.exec(DeviceChooserDialog.java:703)
    at com.android.ide.eclipse.adt.internal.launch.DeviceChooserDialog.deviceChanged(DeviceChooserDialog.java:636)
    at com.android.ddmlib.AndroidDebugBridge.deviceChanged(AndroidDebugBridge.java:876)
    at com.android.ddmlib.Device.update(Device.java:745)
    at com.android.ddmlib.DeviceMonitor.updateDevices(DeviceMonitor.java:364)
    at com.android.ddmlib.DeviceMonitor.processIncomingDeviceData(DeviceMonitor.java:325)
    at com.android.ddmlib.DeviceMonitor.deviceMonitorLoop(DeviceMonitor.java:193)
    at com.android.ddmlib.DeviceMonitor.access$000(DeviceMonitor.java:44)
    at com.android.ddmlib.DeviceMonitor$1.run(DeviceMonitor.java:84)

**Comment by ikkiChung** [comment]
this log is too short,it just says something is null.
so you need to check if anybody be used before initiate.

2014-06-14 20:38 GMT+08:00 abhirajgupta notifications@github.com:

> dude , it is installing on the device , it says
> 2014-06-14 18:05:44 - ddms] null
> java.lang.NullPointerException
> at
> com.android.ide.eclipse.adt.internal.launch.DeviceChooserDialog.exec(DeviceChooserDialog.java:703)
> at
> com.android.ide.eclipse.adt.internal.launch.DeviceChooserDialog.deviceChanged(DeviceChooserDialog.java:636)
> at
> com.android.ddmlib.AndroidDebugBridge.deviceChanged(AndroidDebugBridge.java:876)
> at com.android.ddmlib.Device.update(Device.java:745)
> at com.android.ddmlib.DeviceMonitor.updateDevices(DeviceMonitor.java:364)
> at
> com.android.ddmlib.DeviceMonitor.processIncomingDeviceData(DeviceMonitor.java:325)
> at
> com.android.ddmlib.DeviceMonitor.deviceMonitorLoop(DeviceMonitor.java:193)
> at com.android.ddmlib.DeviceMonitor.access$000(DeviceMonitor.java:44)
> at com.android.ddmlib.DeviceMonitor$1.run(DeviceMonitor.java:84)
> 
> ## 
> 
> Reply to this email directly or view it on GitHub
> https://github.com/ikkiChung/MyRealTimeImageProcessing/issues/1.

## 

Best Regards,
YI HUI, CHUNG
http://smims.com/
SMIMS Tech Ltd.
We create Smart, Multiple, Integrated, Media System
